export type LocalizedText = { zh: string; en: string };

export type Scenario = {
  slug: string;
  icon: string;
  title: LocalizedText;
  summary: LocalizedText;
  audience: LocalizedText;
  categories: string[];
  recommendedTools?: string[];
  flow: LocalizedText[];
};

export const scenarios: Scenario[] = [
  {
    slug: 'ai-customer-service', icon: '◎',
    title: { zh: '搭建 AI 智能客服', en: 'Build an AI customer service agent' },
    summary: { zh: '把知识库、对话模型、工单系统和人工接管串成一套可追踪的服务流程', en: 'Connect a knowledge base, conversational model, ticketing, and human handoff into one traceable service flow' },
    audience: { zh: '电商、SaaS 与客户支持团队', en: 'Ecommerce, SaaS, and customer support teams' },
    categories: ['知识与内容', '模型与文本', '智能体框架', '邮件与通信'],
    recommendedTools: ['langchain-js', 'hugging-face', 'context7'],
    flow: [
      { zh: '接收网页、App 或社交渠道的用户问题', en: 'Receive questions from web, app, or social channels' },
      { zh: '检索已授权的产品知识与历史答案', en: 'Retrieve approved product knowledge and prior answers' },
      { zh: '生成有引用、可控语气的回复', en: 'Generate cited responses in a controlled tone' },
      { zh: '低置信度问题创建工单并转人工', en: 'Create a ticket and hand off low-confidence requests' },
      { zh: '记录解决率、满意度与知识缺口', en: 'Track resolution rate, satisfaction, and knowledge gaps' },
    ],
  },
  {
    slug: 'automated-research', icon: '⌕',
    title: { zh: '自动化调研与情报', en: 'Automate research and intelligence' },
    summary: { zh: '持续完成多源搜索、正文抽取、交叉核验、分析归纳与报告输出', en: 'Continuously search multiple sources, extract content, cross-check facts, analyze findings, and produce reports' },
    audience: { zh: '战略、投资、咨询与市场研究团队', en: 'Strategy, investment, consulting, and market research teams' },
    categories: ['网络服务', '新闻与媒体', '模型与文本', '科学与研究'],
    recommendedTools: ['nasa-open-apis', 'open-library', 'rest-countries', 'nominatim'],
    flow: [
      { zh: '把研究问题拆成关键词、实体与时间范围', en: 'Break the research question into keywords, entities, and time ranges' },
      { zh: '并行搜索公开网页、新闻与专业数据源', en: 'Search public web, news, and specialist data sources in parallel' },
      { zh: '抽取正文、日期、作者与原始链接', en: 'Extract body text, dates, authors, and source links' },
      { zh: '交叉核验关键事实并标注证据强度', en: 'Cross-check key claims and label evidence strength' },
      { zh: '生成带引用的结论、风险和行动建议', en: 'Produce cited findings, risks, and recommended actions' },
    ],
  },
  {
    slug: 'business-data-copilot', icon: '⌁',
    title: { zh: '让 AI 连接业务数据', en: 'Connect business data to AI' },
    summary: { zh: '在权限、审计和数据边界内，让团队用自然语言查询内部业务数据', en: 'Let teams query internal business data in natural language within permission, audit, and data boundaries' },
    audience: { zh: '运营、财务、产品与数据团队', en: 'Operations, finance, product, and data teams' },
    categories: ['云存储与文件', '数据与校验', '安全与认证', '智能体框架'],
    recommendedTools: ['langchain-js', 'hugging-face', 'rest-countries'],
    flow: [
      { zh: '统一数据库、文档和业务接口的只读访问', en: 'Unify read-only access to databases, documents, and business APIs' },
      { zh: '按用户身份注入行列级权限', en: 'Apply row- and column-level access by user identity' },
      { zh: '把问题转换为受约束的查询或工具调用', en: 'Turn questions into constrained queries or tool calls' },
      { zh: '返回带数据来源和计算口径的答案', en: 'Return answers with sources and calculation definitions' },
      { zh: '审计敏感访问、失败查询与导出行为', en: 'Audit sensitive access, failed queries, and exports' },
    ],
  },
  {
    slug: 'content-production', icon: '✦',
    title: { zh: '构建内容生产工作流', en: 'Launch a content production workflow' },
    summary: { zh: '从选题、文案、图片和视频到审核发布，建立可复用的多渠道内容流水线', en: 'Build a reusable multichannel pipeline from ideation and copy to visuals, review, and publishing' },
    audience: { zh: '品牌、增长、新媒体与内容团队', en: 'Brand, growth, social media, and content teams' },
    categories: ['模型与文本', '艺术与设计', '音乐与视频', '日历与活动'],
    recommendedTools: ['hugging-face', 'langchain-js'],
    flow: [
      { zh: '汇总品牌规范、受众和渠道目标', en: 'Collect brand rules, audience context, and channel goals' },
      { zh: '生成选题、内容大纲和素材清单', en: 'Generate topics, outlines, and asset lists' },
      { zh: '并行生产文案、图片、音频或视频', en: 'Produce copy, images, audio, or video in parallel' },
      { zh: '执行事实、版权和品牌一致性审核', en: 'Review facts, rights, and brand consistency' },
      { zh: '排期发布并回收表现数据优化模板', en: 'Schedule publishing and improve templates from performance data' },
    ],
  },
  {
    slug: 'enterprise-knowledge-base', icon: '≡',
    title: { zh: '企业文档知识库', en: 'Build an enterprise knowledge base' },
    summary: { zh: '把分散文档转成带权限、引用与版本控制的内部问答知识库', en: 'Turn scattered documents into an internal Q&A knowledge base with permissions, citations, and version control' },
    audience: { zh: '企业 IT、知识管理与内部支持团队', en: 'Enterprise IT, knowledge management, and internal support teams' },
    categories: ['云存储与文件', '知识与内容', '模型与文本', '安全与认证'],
    recommendedTools: ['open-library', 'langchain-js', 'context7', 'hugging-face'],
    flow: [
      { zh: '同步网盘、Wiki、PDF 与业务文档', en: 'Sync drives, wikis, PDFs, and business documents' },
      { zh: '解析、去重、分块并保留访问权限', en: 'Parse, deduplicate, chunk, and preserve access rights' },
      { zh: '建立可增量更新的检索索引', en: 'Build an incrementally updated retrieval index' },
      { zh: '回答问题并展示命中的原文引用', en: 'Answer questions and show matched source citations' },
      { zh: '监控过期内容、无答案问题和使用反馈', en: 'Monitor stale content, unanswered questions, and feedback' },
    ],
  },
  {
    slug: 'code-review-assistant', icon: '{ }',
    title: { zh: '代码审查助手', en: 'Create a code review assistant' },
    summary: { zh: '在合并请求中自动识别缺陷、安全风险、性能问题和缺失测试', en: 'Automatically identify defects, security risks, performance issues, and missing tests in pull requests' },
    audience: { zh: '研发团队、平台工程与技术负责人', en: 'Engineering teams, platform engineers, and technical leads' },
    categories: ['开发者工具', '模型与文本', '安全与认证', '数据与校验'],
    recommendedTools: ['github-rest-api', 'context7', 'playwright-mcp', 'mcp-typescript-sdk'],
    flow: [
      { zh: '接收提交差异、仓库规范和相关代码上下文', en: 'Ingest diffs, repository rules, and related code context' },
      { zh: '运行静态检查、测试和依赖安全扫描', en: 'Run static checks, tests, and dependency security scans' },
      { zh: '让模型定位高置信度问题并解释影响', en: 'Use a model to locate high-confidence issues and explain impact' },
      { zh: '把建议绑定到具体文件与行号', en: 'Attach recommendations to exact files and lines' },
      { zh: '跟踪误报、采纳率和回归缺陷', en: 'Track false positives, adoption, and escaped defects' },
    ],
  },
  {
    slug: 'sales-lead-scoring', icon: '↗',
    title: { zh: '销售线索评分', en: 'Score and route sales leads' },
    summary: { zh: '合并客户行为、公司信息和沟通记录，为销售生成优先级与下一步动作', en: 'Combine behavior, company data, and conversations to give sales teams priorities and next actions' },
    audience: { zh: 'B2B 销售、增长运营与收入团队', en: 'B2B sales, growth operations, and revenue teams' },
    categories: ['商业与金融', '公共数据', '模型与文本', '邮件与通信'],
    recommendedTools: ['rest-countries', 'nominatim', 'langchain-js'],
    flow: [
      { zh: '汇总表单、访问行为、CRM 与公开公司信息', en: 'Combine forms, product activity, CRM, and public company data' },
      { zh: '校验联系人与公司实体并补全字段', en: 'Validate contacts and companies and enrich missing fields' },
      { zh: '按意向、匹配度和时效计算评分', en: 'Score intent, fit, and recency' },
      { zh: '生成个性化触达建议并分配销售', en: 'Generate personalized outreach and assign an owner' },
      { zh: '根据成交结果持续校准评分规则', en: 'Calibrate scoring rules from conversion outcomes' },
    ],
  },
  {
    slug: 'marketing-campaign', icon: '%',
    title: { zh: '营销活动策划', en: 'Plan a marketing campaign' },
    summary: { zh: '把市场洞察转成受众、信息、渠道、素材与复盘指标完整方案', en: 'Turn market insight into a complete audience, message, channel, creative, and measurement plan' },
    audience: { zh: '品牌营销、增长与活动运营团队', en: 'Brand marketing, growth, and campaign operations teams' },
    categories: ['商业与金融', '新闻与媒体', '艺术与设计', '模型与文本'],
    recommendedTools: ['rest-countries', 'nominatim', 'open-library', 'hugging-face'],
    flow: [
      { zh: '分析市场、竞品、受众与历史活动', en: 'Analyze market, competitors, audiences, and prior campaigns' },
      { zh: '确定活动目标、核心信息和细分人群', en: 'Define objectives, core messages, and segments' },
      { zh: '生成渠道策略、创意方向和内容日历', en: 'Create channel strategy, creative directions, and a content calendar' },
      { zh: '审核品牌、事实与平台合规要求', en: 'Review brand, factual, and platform compliance' },
      { zh: '跟踪成本、转化和增量效果并复盘', en: 'Track cost, conversion, and incremental impact' },
    ],
  },
  {
    slug: 'product-recommendation', icon: '◇',
    title: { zh: '商品智能推荐', en: 'Build product recommendations' },
    summary: { zh: '结合商品、用户与实时行为生成可解释、可运营的个性化推荐', en: 'Use catalog, customer, and real-time behavior data to produce explainable, operable recommendations' },
    audience: { zh: '电商、零售、内容平台与产品团队', en: 'Ecommerce, retail, content platforms, and product teams' },
    categories: ['商业与金融', '数据与校验', '模型与推理', '云存储与文件'],
    flow: [
      { zh: '清洗商品目录、库存与用户行为事件', en: 'Clean catalog, inventory, and user behavior events' },
      { zh: '构建用户兴趣、商品属性和场景特征', en: 'Build user interest, item attribute, and context features' },
      { zh: '生成候选并按业务规则重新排序', en: 'Generate candidates and rerank with business rules' },
      { zh: '返回推荐理由并过滤不可售商品', en: 'Return recommendation reasons and filter unavailable items' },
      { zh: '通过实验评估点击、转化与长期价值', en: 'Evaluate clicks, conversion, and long-term value with experiments' },
    ],
  },
  {
    slug: 'data-dashboard', icon: '▦',
    title: { zh: '经营数据驾驶舱', en: 'Create an operations dashboard' },
    summary: { zh: '自动汇总核心指标、异常变化和原因解释，帮助管理者快速决策', en: 'Automatically assemble key metrics, anomalies, and explanations to help leaders decide faster' },
    audience: { zh: '管理层、经营分析与业务负责人', en: 'Executives, business analysts, and functional leaders' },
    categories: ['数据与校验', '商业与金融', '云存储与文件', '模型与文本'],
    flow: [
      { zh: '接入财务、销售、产品和运营数据', en: 'Connect finance, sales, product, and operations data' },
      { zh: '统一指标口径并执行质量校验', en: 'Standardize metric definitions and validate quality' },
      { zh: '计算趋势、同比环比和异常信号', en: 'Calculate trends, comparisons, and anomaly signals' },
      { zh: '生成原因解释、影响范围和行动提示', en: 'Generate cause hypotheses, impact, and action prompts' },
      { zh: '按角色分发日报、周报和预警', en: 'Distribute role-based daily reports, weekly reports, and alerts' },
    ],
  },
  {
    slug: 'meeting-copilot', icon: '□',
    title: { zh: '会议智能助手', en: 'Build a meeting copilot' },
    summary: { zh: '完成会前准备、实时转写、结论提炼、任务分派和会后跟进', en: 'Handle meeting preparation, transcription, decisions, task assignment, and follow-up' },
    audience: { zh: '项目团队、销售、客户成功与管理者', en: 'Project teams, sales, customer success, and managers' },
    categories: ['音乐与视频', '日历与活动', '模型与文本', '邮件与通信'],
    flow: [
      { zh: '读取日程、参会人和相关项目资料', en: 'Read the calendar, attendees, and related project material' },
      { zh: '生成议程、问题清单和会前简报', en: 'Generate an agenda, questions, and a pre-read' },
      { zh: '实时转写并区分说话人和关键片段', en: 'Transcribe in real time with speakers and key moments' },
      { zh: '提炼决定、风险、负责人和截止日期', en: 'Extract decisions, risks, owners, and due dates' },
      { zh: '同步任务系统并自动发送跟进提醒', en: 'Sync tasks and send follow-up reminders automatically' },
    ],
  },
  {
    slug: 'email-automation', icon: '@',
    title: { zh: '智能邮件自动化', en: 'Automate intelligent email' },
    summary: { zh: '分类来信、提取任务、生成草稿并在风险规则内自动回复', en: 'Classify messages, extract tasks, draft responses, and auto-reply within risk rules' },
    audience: { zh: '运营、销售、客服与行政团队', en: 'Operations, sales, support, and administrative teams' },
    categories: ['邮件与通信', '模型与文本', '安全与认证', '智能体框架'],
    flow: [
      { zh: '通过授权邮箱接收邮件和线程上下文', en: 'Receive messages and thread context through authorized mailboxes' },
      { zh: '识别意图、优先级、情绪和敏感信息', en: 'Identify intent, priority, sentiment, and sensitive information' },
      { zh: '检索客户与业务信息生成回复草稿', en: 'Retrieve customer and business context to draft a reply' },
      { zh: '按风险阈值自动发送或请求人工审批', en: 'Send automatically or request approval based on risk' },
      { zh: '记录处理时长、升级率和回复质量', en: 'Track handling time, escalation rate, and response quality' },
    ],
  },
  {
    slug: 'contract-review', icon: '⚖',
    title: { zh: '合同审阅与风险提示', en: 'Review contracts and flag risk' },
    summary: { zh: '抽取关键条款、对比标准模板、标注风险并生成可审计的审阅意见', en: 'Extract key clauses, compare playbooks, flag risks, and produce auditable review notes' },
    audience: { zh: '法务、采购、销售运营与合规团队', en: 'Legal, procurement, sales operations, and compliance teams' },
    categories: ['云存储与文件', '知识与内容', '模型与文本', '安全与认证'],
    flow: [
      { zh: '安全上传合同并识别版本和签约主体', en: 'Upload contracts securely and identify versions and parties' },
      { zh: '抽取金额、期限、责任和终止等关键条款', en: 'Extract payment, term, liability, and termination clauses' },
      { zh: '与模板、政策和历史谈判标准对比', en: 'Compare against templates, policy, and negotiation history' },
      { zh: '标注风险等级、原文位置和修改建议', en: 'Flag severity, source location, and suggested edits' },
      { zh: '保存人工结论、审批记录和最终版本', en: 'Store human decisions, approvals, and the final version' },
    ],
  },
  {
    slug: 'invoice-processing', icon: '✓',
    title: { zh: '发票与单据处理', en: 'Process invoices and documents' },
    summary: { zh: '自动识别票据、校验字段、匹配订单并把异常交给人工处理', en: 'Read documents, validate fields, match purchase orders, and route exceptions to people' },
    audience: { zh: '财务、采购、共享服务与运营团队', en: 'Finance, procurement, shared services, and operations teams' },
    categories: ['云存储与文件', '数据与校验', '模型与推理', '商业与金融'],
    flow: [
      { zh: '接收扫描件、PDF、邮件附件与结构化票据', en: 'Receive scans, PDFs, email attachments, and structured invoices' },
      { zh: '识别供应商、金额、税额和明细行', en: 'Extract supplier, total, tax, and line items' },
      { zh: '校验格式、重复票据和税务规则', en: 'Validate formats, duplicates, and tax rules' },
      { zh: '匹配订单、收货记录并标记差异', en: 'Match purchase orders and receipts and flag discrepancies' },
      { zh: '自动入账低风险单据并分派异常', en: 'Post low-risk documents and assign exceptions' },
    ],
  },
  {
    slug: 'feedback-analysis', icon: '◉',
    title: { zh: '用户反馈洞察', en: 'Analyze customer feedback' },
    summary: { zh: '聚合评论、工单和访谈，识别主题、情绪、影响人群与产品机会', en: 'Combine reviews, tickets, and interviews to identify themes, sentiment, affected users, and product opportunities' },
    audience: { zh: '产品、客户成功、研究与体验团队', en: 'Product, customer success, research, and experience teams' },
    categories: ['模型与文本', '数据与校验', '商业与金融', '知识与内容'],
    flow: [
      { zh: '汇总应用评论、问卷、工单与访谈记录', en: 'Aggregate app reviews, surveys, tickets, and interview notes' },
      { zh: '清洗重复内容并去除个人敏感信息', en: 'Deduplicate content and remove personal information' },
      { zh: '识别主题、情绪、严重度和用户类型', en: 'Identify topics, sentiment, severity, and user segments' },
      { zh: '关联产品版本、功能和业务指标', en: 'Link feedback to product versions, features, and metrics' },
      { zh: '输出机会清单并跟踪处理后的变化', en: 'Publish an opportunity backlog and track post-fix changes' },
    ],
  },
  {
    slug: 'social-listening', icon: '◫',
    title: { zh: '社交舆情监测', en: 'Monitor social and media signals' },
    summary: { zh: '持续监控品牌、产品和竞品讨论，识别异常趋势与需要响应的风险', en: 'Continuously monitor brand, product, and competitor conversations for unusual trends and response-worthy risks' },
    audience: { zh: '公关、品牌、市场与风险团队', en: 'Communications, brand, marketing, and risk teams' },
    categories: ['新闻与媒体', '网络服务', '模型与文本', '数据与校验'],
    flow: [
      { zh: '配置品牌、产品、人物和竞品关键词', en: 'Configure brand, product, executive, and competitor keywords' },
      { zh: '采集新闻、论坛、社交与搜索趋势', en: 'Collect news, forums, social posts, and search trends' },
      { zh: '去重并识别语言、情绪、主题和传播者', en: 'Deduplicate and detect language, sentiment, topic, and influencers' },
      { zh: '按声量变化和风险规则触发预警', en: 'Trigger alerts from volume changes and risk rules' },
      { zh: '生成事件摘要、证据链接和响应建议', en: 'Generate incident summaries, evidence links, and response options' },
    ],
  },
  {
    slug: 'multilingual-localization', icon: '文',
    title: { zh: '多语言内容本地化', en: 'Localize content at scale' },
    summary: { zh: '在术语、品牌语气和地区规则约束下批量翻译并持续同步内容', en: 'Translate and continuously synchronize content under terminology, brand voice, and regional rules' },
    audience: { zh: '国际化、产品、内容与本地运营团队', en: 'Localization, product, content, and regional operations teams' },
    categories: ['模型与文本', '知识与内容', '数据与校验', '开发者工具'],
    flow: [
      { zh: '提取界面、帮助中心和营销内容', en: 'Extract product UI, help center, and marketing content' },
      { zh: '加载术语库、品牌语气和地区禁用规则', en: 'Load terminology, brand voice, and regional restrictions' },
      { zh: '按上下文翻译并保留变量和格式', en: 'Translate in context while preserving variables and formatting' },
      { zh: '执行一致性、长度和敏感内容检查', en: 'Check consistency, length, and sensitive content' },
      { zh: '人工抽检后发布并同步后续变更', en: 'Sample-review, publish, and synchronize future changes' },
    ],
  },
  {
    slug: 'image-design-pipeline', icon: '✦',
    title: { zh: '品牌图片设计流水线', en: 'Build a brand image pipeline' },
    summary: { zh: '把创意简报转成符合品牌规范的多尺寸视觉素材与可追溯版本', en: 'Turn creative briefs into traceable, brand-compliant visual assets across sizes' },
    audience: { zh: '品牌、电商、设计与社交媒体团队', en: 'Brand, ecommerce, design, and social media teams' },
    categories: ['艺术与设计', '模型与文本', '云存储与文件', '数据与校验'],
    flow: [
      { zh: '结构化创意目标、受众、渠道和尺寸', en: 'Structure creative goals, audience, channels, and sizes' },
      { zh: '检索品牌资产、参考图与禁用元素', en: 'Retrieve brand assets, references, and prohibited elements' },
      { zh: '生成多个视觉方向和文案组合', en: 'Generate multiple visual directions and copy combinations' },
      { zh: '检查文字、商标、安全区与品牌色', en: 'Check text, trademarks, safe areas, and brand colors' },
      { zh: '导出渠道规格并记录提示词与版本', en: 'Export channel variants and record prompts and versions' },
    ],
  },
  {
    slug: 'video-production', icon: '♫',
    title: { zh: '短视频自动生产', en: 'Automate short-form video production' },
    summary: { zh: '从脚本、配音、画面到字幕和多平台导出，形成稳定的视频生产链路', en: 'Create a stable pipeline from scripts, voice, and visuals to captions and multichannel exports' },
    audience: { zh: '新媒体、营销、电商与培训团队', en: 'Social, marketing, ecommerce, and training teams' },
    categories: ['音乐与视频', '模型与文本', '艺术与设计', '云存储与文件'],
    flow: [
      { zh: '根据目标时长和渠道生成脚本与分镜', en: 'Generate scripts and storyboards for the target duration and channel' },
      { zh: '准备画面素材、配音、音乐和音效', en: 'Prepare visuals, voiceover, music, and sound effects' },
      { zh: '合成镜头并按节奏自动剪辑', en: 'Compose shots and edit to rhythm automatically' },
      { zh: '生成字幕并执行版权与内容安全检查', en: 'Generate captions and check rights and content safety' },
      { zh: '输出多比例版本并分析完播表现', en: 'Export multiple aspect ratios and analyze completion performance' },
    ],
  },
  {
    slug: 'voice-assistant', icon: '◉',
    title: { zh: '实时语音助手', en: 'Build a real-time voice assistant' },
    summary: { zh: '用低延迟语音识别、推理、工具调用和语音合成完成自然对话', en: 'Combine low-latency speech recognition, reasoning, tool use, and synthesis for natural conversations' },
    audience: { zh: '智能硬件、客服、车载与无障碍产品团队', en: 'Smart-device, support, automotive, and accessibility teams' },
    categories: ['音乐与视频', '模型与推理', '智能体框架', '网络服务'],
    flow: [
      { zh: '采集音频并执行降噪、端点和语言检测', en: 'Capture audio and detect noise, endpoints, and language' },
      { zh: '流式转写并维护多轮会话上下文', en: 'Stream transcription and maintain conversation context' },
      { zh: '判断意图并安全调用外部工具', en: 'Resolve intent and call external tools safely' },
      { zh: '生成简洁答复并流式合成语音', en: 'Generate concise replies and stream synthesized speech' },
      { zh: '监控端到端延迟、中断率和任务成功率', en: 'Monitor end-to-end latency, interruption, and task success' },
    ],
  },
  {
    slug: 'fraud-monitoring', icon: '⬡',
    title: { zh: '欺诈与风险监测', en: 'Monitor fraud and operational risk' },
    summary: { zh: '结合实时规则、异常检测和人工复核，识别高风险交易与账户行为', en: 'Combine real-time rules, anomaly detection, and human review to identify risky transactions and account behavior' },
    audience: { zh: '金融、支付、电商风控与安全团队', en: 'Finance, payments, ecommerce risk, and security teams' },
    categories: ['安全与认证', '金融数据', '数据与校验', '模型与推理'],
    flow: [
      { zh: '采集交易、设备、账户与行为事件', en: 'Collect transaction, device, account, and behavior events' },
      { zh: '校验身份并计算规则与异常特征', en: 'Verify identity and calculate rules and anomaly features' },
      { zh: '生成风险分数、原因码和证据链', en: 'Produce a risk score, reason codes, and evidence trail' },
      { zh: '按阈值放行、拦截或进入人工复核', en: 'Approve, block, or route to manual review by threshold' },
      { zh: '用确认结果监控漂移并更新策略', en: 'Use confirmed outcomes to monitor drift and update policy' },
    ],
  },
  {
    slug: 'developer-docs-assistant', icon: '⌘',
    title: { zh: '开发者文档助手', en: 'Create a developer docs assistant' },
    summary: { zh: '把 API、代码仓库和变更记录组织成版本匹配、可执行的开发问答', en: 'Organize APIs, repositories, and changelogs into version-matched, actionable developer answers' },
    audience: { zh: '开发者关系、平台团队与软件产品团队', en: 'Developer relations, platform teams, and software product teams' },
    categories: ['开发者工具', '知识与内容', '模型与文本', '数据与校验'],
    flow: [
      { zh: '同步文档、OpenAPI、示例代码和版本记录', en: 'Sync docs, OpenAPI specs, sample code, and release notes' },
      { zh: '按产品版本、语言和框架建立索引', en: 'Index by product version, language, and framework' },
      { zh: '识别问题上下文并检索匹配的资料', en: 'Resolve question context and retrieve matching material' },
      { zh: '生成带来源的解释和最小代码示例', en: 'Generate sourced explanations and minimal code examples' },
      { zh: '执行示例检查并收集未解决问题', en: 'Validate examples and collect unresolved questions' },
    ],
  },
  {
    slug: 'recruiting-screening', icon: '♧',
    title: { zh: '招聘流程助手', en: 'Assist the recruiting workflow' },
    summary: { zh: '结构化岗位与候选人信息，辅助筛选、面试准备和流程跟进', en: 'Structure role and candidate information to assist screening, interview preparation, and process follow-up' },
    audience: { zh: '招聘、人力资源与用人团队', en: 'Recruiting, HR, and hiring teams' },
    categories: ['模型与文本', '日历与活动', '邮件与通信', '数据与校验'],
    flow: [
      { zh: '结构化岗位要求并移除歧视性条件', en: 'Structure role requirements and remove discriminatory criteria' },
      { zh: '解析候选人经历、技能与作品证据', en: 'Parse candidate experience, skills, and portfolio evidence' },
      { zh: '按公开标准生成辅助匹配结果', en: 'Produce assistive matches against published criteria' },
      { zh: '生成人工面试问题并安排沟通', en: 'Generate human interview questions and schedule communication' },
      { zh: '记录人工决定并审计公平性指标', en: 'Record human decisions and audit fairness metrics' },
    ],
  },
  {
    slug: 'personalized-learning', icon: '+',
    title: { zh: '个性化学习助手', en: 'Build a personalized learning tutor' },
    summary: { zh: '根据学习目标、掌握程度和反馈动态生成讲解、练习与复习计划', en: 'Adapt explanations, practice, and review plans to learning goals, mastery, and feedback' },
    audience: { zh: '教育产品、企业培训、教师与学习者', en: 'Education products, corporate training, teachers, and learners' },
    categories: ['知识与内容', '模型与文本', '科学与研究', '数据与校验'],
    flow: [
      { zh: '定义课程目标、知识点和先修关系', en: 'Define learning objectives, concepts, and prerequisites' },
      { zh: '通过测评识别掌握度与知识缺口', en: 'Assess mastery and identify knowledge gaps' },
      { zh: '检索可靠材料并生成分层讲解', en: 'Retrieve reliable material and generate tiered explanations' },
      { zh: '生成练习、提示和即时反馈', en: 'Generate exercises, hints, and immediate feedback' },
      { zh: '按遗忘曲线调整复习与学习路径', en: 'Adjust review and learning paths using retention signals' },
    ],
  },
  {
    slug: 'health-information-assistant', icon: '+',
    title: { zh: '健康信息助手', en: 'Create a health information assistant' },
    summary: { zh: '基于可信资料提供健康知识检索、通俗解释与明确的就医边界', en: 'Provide health information retrieval and plain-language explanations from trusted sources with clear care boundaries' },
    audience: { zh: '健康内容、患者教育与公共服务团队', en: 'Health content, patient education, and public service teams' },
    categories: ['科学与健康', '知识与内容', '模型与文本', '安全与认证'],
    flow: [
      { zh: '识别问题、地区、语言和紧急风险信号', en: 'Identify the question, region, language, and emergency risk signals' },
      { zh: '仅检索经过审核的权威健康资料', en: 'Retrieve only reviewed, authoritative health sources' },
      { zh: '生成通俗解释并展示资料来源', en: 'Generate plain-language explanations with sources' },
      { zh: '避免诊断处方并提示适当就医渠道', en: 'Avoid diagnosis or prescribing and direct users to appropriate care' },
      { zh: '记录高风险拦截和内容质量反馈', en: 'Log high-risk interventions and content quality feedback' },
    ],
  },
  {
    slug: 'travel-planner', icon: '◎',
    title: { zh: '智能旅行规划', en: 'Build an intelligent trip planner' },
    summary: { zh: '结合时间、预算、天气与兴趣生成可调整、可核验的旅行行程', en: 'Combine time, budget, weather, and interests into an editable, verifiable itinerary' },
    audience: { zh: '旅行平台、内容产品与个人效率工具', en: 'Travel platforms, content products, and personal productivity tools' },
    categories: ['天气与地理', '日历与活动', '公共数据', '模型与文本'],
    flow: [
      { zh: '收集目的地、日期、预算、偏好与限制', en: 'Collect destination, dates, budget, preferences, and constraints' },
      { zh: '查询地点、交通、营业时间和天气信息', en: 'Query places, transport, opening hours, and weather' },
      { zh: '按地理距离和时间窗口组织每日行程', en: 'Organize daily plans by distance and time windows' },
      { zh: '标注价格、预约要求、来源与备选项', en: 'Show prices, booking requirements, sources, and alternatives' },
      { zh: '根据天气或用户变更实时重排计划', en: 'Replan when weather or user constraints change' },
    ],
  },
  {
    slug: 'financial-reporting', icon: '%',
    title: { zh: '财务分析与报告', en: 'Automate financial analysis and reporting' },
    summary: { zh: '整合财务数据、执行对账和差异分析，生成带口径与来源的经营报告', en: 'Combine finance data, reconcile records, analyze variance, and produce reports with definitions and sources' },
    audience: { zh: '财务、审计、经营分析与管理层', en: 'Finance, audit, business analysis, and leadership teams' },
    categories: ['金融数据', '商业与金融', '数据与校验', '模型与文本'],
    flow: [
      { zh: '接入总账、预算、银行与业务系统数据', en: 'Connect ledger, budget, bank, and operating system data' },
      { zh: '统一科目、期间和币种并执行对账', en: 'Normalize accounts, periods, and currencies and reconcile' },
      { zh: '计算差异、趋势和异常明细', en: 'Calculate variance, trends, and anomaly details' },
      { zh: '生成带数据引用的管理层解释', en: 'Generate management commentary with data citations' },
      { zh: '锁定版本、审批发布并保留审计记录', en: 'Lock versions, approve publication, and preserve audit trails' },
    ],
  },
];

export const getScenario = (slug: string) => scenarios.find((scenario) => scenario.slug === slug);
